[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:Type google._upb._message.*:DeprecationWarning
    ignore:pkg_resources is deprecated as an API:DeprecationWarning
    ignore:Deprecated call to `pkg_resources.declare_namespace.*:DeprecationWarning
    ignore:Pydantic V1 style .* validators are deprecated.*:DeprecationWarning:mlflow.gateway.config
    ignore:Support for class-based `config` is deprecated.*:DeprecationWarning:pydantic._internal._config
